name: dockerAction

on:
  push:

jobs:
  test-docker-action:
    name: job to test our docker action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x entrypoint.sh
      - uses: ./
        id: dockerAction
        with:
          number1: 35
          number2: 58
      - run: echo ${{ steps.dockerAction.result }}
      - run: cat $GIHUB_WORKSPACE/containerOutputFile.txt
      - run: cat ${{ github.workspace }}/containerOutputFile.txt
